using System;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Serialization;
using Microsoft.Build.Utilities;
using Wckdrzr.AutomaticBuildNumber.Config;

namespace Wckdrzr.AutomaticBuildNumber.IO
{
	public class FileServices
	{
		public PropertyGroup config;
		private string ConfigFilename;
		private Serializer xmlSerializer;
		private const string APPLICATION_NAME = "AutoBuildNumber";
		private const string CSPROJ_PATH = "../../../";

		public FileServices()
		{
			xmlSerializer = new Serializer();	

			Project CSProjectFile = xmlSerializer.Deserialize<Project>(File.ReadAllText(GetPropertyFileLocation()));

			for (int i=0; i<CSProjectFile.PropertyGroup.Count; i++)
			{
				if (CSProjectFile.PropertyGroup[i].Label == APPLICATION_NAME)
				{
					config = CSProjectFile.PropertyGroup[i];
				}
            }

			if (config == null)
				config = CreateDefaultConfig();
		}

		private string GetPropertyFileLocation()
        {
			DirectoryInfo di = new DirectoryInfo(CSPROJ_PATH);
			FileInfo[] projectFile = di.GetFiles("*.csproj");

			if (projectFile.Count() > 1)
				throw new Exception("More than one project file was found");

			return projectFile[0].FullName;
		}

        private PropertyGroup CreateDefaultConfig()
        {
			PropertyGroup defaultConfig = new PropertyGroup{ Label = APPLICATION_NAME, MajorVersion = 0, MinorVersion = 0, RevisionVersion = 1, BuildNumber=0, IsDefaultConfig = true};
			return defaultConfig;
        }

        public bool WriteAppConfig()
        {
			string newPropertyString = xmlSerializer.Serialize<PropertyGroup>(config);

			try
			{
				string fileContents = File.ReadAllText(GetPropertyFileLocation());
				XmlDocument projFileXML = new XmlDocument();
				projFileXML.LoadXml(fileContents);

				XmlDocument tempDoc = new XmlDocument();
				tempDoc.LoadXml(newPropertyString);

				XmlNode oldNode;
				XmlNode parent;

				//check if we've loaded config or created a default
				if (!config.IsDefaultConfig)
				{
					oldNode = projFileXML.SelectSingleNode("/Project/PropertyGroup[@Label='AutoBuildNumber']");
					parent = oldNode.ParentNode;
					parent.RemoveChild(oldNode);
				}
				else
                {
					oldNode = projFileXML.SelectSingleNode("/Project");
					parent = oldNode;
				}

				XmlNode newNode = tempDoc.DocumentElement;
				XmlNode importedNode = projFileXML.ImportNode(newNode, true);
				parent.AppendChild(importedNode);

				var settings = new XmlWriterSettings
				{
					Indent = true,
					OmitXmlDeclaration = true
				};

				var ns = new XmlSerializerNamespaces(new[] { XmlQualifiedName.Empty });

				using (var stream = new StreamWriter(GetPropertyFileLocation()))
				using (var writer = XmlWriter.Create(stream, settings))
				{
					projFileXML.Save(writer);
				}
			}
			catch (Exception ex)
			{
				Console.WriteLine($"Error Encountered updating the dotnet Project File: {ex.Message}");
				return false;
			}
			return true;
		}

		public bool WriteAssemblyInfoFile()
		{
            string[] fileContents =
            {
                "using System.Reflection;",
                "using System.Runtime.InteropServices;",
                " ",
                $"[assembly: AssemblyVersion(\"{config.VersionNumber()}\")]"
            };

            try
            {
				string filename = "VersionInfo";

				if (string.IsNullOrEmpty(config.VersionInformationFilename))
				{
					filename = config.VersionInformationFilename;
				}
				
				File.WriteAllLines($"../../../{filename}.cs", fileContents);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error Encountered: {ex.Message}");
                return false;
            }

            return true;
		}

		public bool WriteVersionRoute()
        {
			string[] fileContents =
			{
			"using Microsoft.AspNetCore.Mvc;",
			" ",
			"namespace WCKDRZR.AutoGenerated.Controllers",
			"{",
			"	[ApiController]",
			"	public class VersionController : ControllerBase",
			"	{",
			"		[HttpGet]",
			"		[Route(\"[controller]\")]",
			"		public string Get()",
			"       {",
			"			return System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString();",
			"		}",
			"	}",
			"}"
			};

			try
			{
				File.WriteAllLines($"../../../Controllers/VersionController.cs", fileContents);
			}
			catch (Exception ex)
			{
				Console.WriteLine($"Error Encountered: {ex.Message}");
				return false;
			}

			return true;
		}
	}
}

