using System;
using System.IO;
using System.Linq;
using System.Xml;
using System.Xml.Serialization;
using Wckdrzr.AutomaticVersionUpdate.Config;

namespace Wckdrzr.AutomaticVersionUpdate.IO
{
	public class FileServices
	{
		public readonly PropertyGroup Config;
		private readonly Serializer _xmlSerializer;
		private const string ApplicationName = "AutoBuildNumber";
		private const string CsprojPath = "./";

		public FileServices()
		{
			_xmlSerializer = new Serializer();	

			Project csProjectFile = _xmlSerializer.Deserialize<Project>(File.ReadAllText(GetPropertyFileLocation()));

			foreach (var propertyGroup in csProjectFile.PropertyGroup)
			{
				if (propertyGroup.Label == ApplicationName)
				{
					Config = propertyGroup;
				}
			}

			if (Config == null)
				Config = CreateDefaultConfig();
		}

		private string GetPropertyFileLocation()
        {
			DirectoryInfo di = new DirectoryInfo(CsprojPath);
			FileInfo[] projectFile = di.GetFiles("*.csproj");

			if (projectFile==null)
				throw new Exception($"Can't find the project file for this project. Current search path:{di.FullName}");
			if (projectFile.Count() > 1)
				throw new Exception("More than one project file was found. Please ensure there is only a single file.");
			
			return projectFile[0].FullName;
		}

        private PropertyGroup CreateDefaultConfig()
        {
			PropertyGroup defaultConfig = new PropertyGroup{ Label = ApplicationName, MajorVersion = 0, MinorVersion = 0, RevisionVersion = 1, BuildNumber=0, IsDefaultConfig = true};
			return defaultConfig;
        }

        public bool WriteAppConfig()
        {
			string newPropertyString = _xmlSerializer.Serialize<PropertyGroup>(Config);

			try
			{
				string fileContents = File.ReadAllText(GetPropertyFileLocation());
				XmlDocument projFileXml = new XmlDocument();
				projFileXml.LoadXml(fileContents);

				XmlDocument tempDoc = new XmlDocument();
				tempDoc.LoadXml(newPropertyString);

				XmlNode oldNode;
				XmlNode parent = null;

				//check if we've loaded config or created a default
				if (!Config.IsDefaultConfig)
				{
					oldNode = projFileXml.SelectSingleNode($"/Project/PropertyGroup[@Label='{ApplicationName}']");
					if (oldNode != null)
					{
						parent = oldNode.ParentNode;
						parent.RemoveChild(oldNode);
					}
				}
				else
                {
					oldNode = projFileXml.SelectSingleNode("/Project");
					parent = oldNode;
				}

				XmlNode newNode = tempDoc.DocumentElement;
				XmlNode importedNode = projFileXml.ImportNode(newNode, true);
				parent.AppendChild(importedNode);

				var settings = new XmlWriterSettings
				{
					Indent = true,
					OmitXmlDeclaration = true
				};

				var ns = new XmlSerializerNamespaces(new[] { XmlQualifiedName.Empty });

				using var stream = new StreamWriter(GetPropertyFileLocation());
				using var writer = XmlWriter.Create(stream, settings);
				projFileXml.Save(writer);
			}
			catch (Exception ex)
			{
				Console.WriteLine($"Error Encountered updating the dotnet Project File: {ex.Message}");
				return false;
			}
			return true;
		}

		public bool WriteAssemblyInfoFile()
		{
            string[] fileContents =
            {
                "using System.Reflection;",
                "using System.Runtime.InteropServices;",
                " ",
                $"[assembly: AssemblyVersion(\"{Config.VersionNumber()}\")]"
            };

            try
            {
				string filename = "VersionInfo";

				if (string.IsNullOrEmpty(Config.VersionInformationFilename))
				{
					filename = Config.VersionInformationFilename;
				}
				
				File.WriteAllLines($"../../../{filename}.cs", fileContents);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error Encountered: {ex.Message}");
                return false;
            }

            return true;
		}

		public bool WriteVersionRoute()
        {
			string[] fileContents =
			{
			"using Microsoft.AspNetCore.Mvc;",
			" ",
			"namespace WCKDRZR.AutoGenerated.Controllers",
			"{",
			"	[ApiController]",
			"	public class VersionController : ControllerBase",
			"	{",
			"		[HttpGet]",
			"		[Route(\"[controller]\")]",
			"		public string Get()",
			"       {",
			"			return System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString();",
			"		}",
			"	}",
			"}"
			};

			try
			{
				File.WriteAllLines($"../../../Controllers/VersionController.cs", fileContents);
			}
			catch (Exception ex)
			{
				Console.WriteLine($"Error Encountered: {ex.Message}");
				return false;
			}

			return true;
		}
	}
}

